spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    username: postgres
    password: pass

  jpa:
    hibername:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
          jdbc:
            lob:
              non_contextual_creation: true

  thymeleaf:
    cache: false